### ISSUE TITLE
话说device_id是怎么获取的？

### ISSUE THREAD

**Issue by RimoChan** [hasscc/meiju#5]
我在美的美居的app里找不到这个值……

**Comment by vividmuse** [comment]
登录的还是物理设备的?

黄巍 ***@***.***> 于2023年7月2日周日 13:12写道：

**Comment by RimoChan** [comment]
就是readme.md里有这样一段config嘛——
```
meiju:
  # Single account
  username: 18866668888 # Username of Meiju APP (美的美居)
  password: abcdefghijk # Password
  devices:
    - device_id: 160123456789001
      host: 192.168.1.101
    - device_id: 160123456789002
      host: 192.168.1.102
```
这里的`160123456789001`，我理解应该是一台物理设备比如洗衣机，这个`160123456789001`应该怎么拿呢？

**Comment by vividmuse** [comment]
这好像是那个脚本解码来的

在 2023年7月4日星期二，黄巍 ***@***.***> 写道：

**Comment by al-one** [comment]
1. 先配置账号密码启动：
  ```yaml
  meiju:
    # Single account
    username: 18866668888 # Username of Meiju APP (美的美居)
    password: abcdefghijk # Password
  ```
2. 通过[HA系统日志](https://my.home-assistant.io/redirect/logs)可以看到账号下的所有设备及其ID
